nreps: 10 
singleton_sample_prob: 1.0
nspecies: 2
ngenomes: 4
nloci: 10
locus_length: 1000
ecoevolity_chains: 4
ecoevolity_chain_length: 750000
starbeast_chains: 2
starbeast_chain_length: 10000000
pop_size_shape: 5.0
pop_size_scale: 0.004
birth_rate: 1.0
templates_path: /gpfs01/home/kac0070/simulation/templates